schema {
  query: Query
  mutation: Mutation
}

scalar Date

type Event {
  date: Date
  id: ID
  slots: [Slot]
}

type Mutation {
  createEvent(date: Date!): Event!
  createPet(age: Int!, name: String!, ownerName: String, pictureUri: String): Pet!
  deletePet(id: ID): ID!
  updatePet(age: Int, id: ID!, name: String, ownerName: String, pictureUri: String): Pet!
}

type Pet {
  age: Int
  id: ID
  name: String
  ownerName: String
  pictureUri: String
}

type Query {
  getEvent(id: ID): Event
  getEvents: [Event]
  getPet(id: ID!): Pet
  getPets: [Pet]
}

type Slot {
  date: Date
  duration: Int
  endDate: Date
  id: ID
  startDate: Date
  title: String
}