name: Pull-Request Check

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install  dependencies
        run: |
          npm install
      - name: run test
        run: |
          npm run verify
          npm run test
      - run: npm ci
