name: Pull-Request Check

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install  dependencies
        run: |
          echo @jhonm:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${GH_TOKEN}' >> .npmrc
          npm install
      - name: run test
        run: |
          npm run verify
          npm run test
      - run: npm ci
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
